safe:        true
markdown: kramdown
exclude: [node_modules, bower_components, vendor]
url: http://jhipster-china.github.io 
github_repository_url: https://github.com/jhipster-china/jhipster-china.github.io
kramdown:
  input: GFM
gems:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
defaults:
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
